"""add users, per-user drive tokens, content search

Revision ID: 5f9846931b54
Revises: 8497f441bf34
Create Date: 2026-07-11 11:44:22.215460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9846931b54'
down_revision = '8497f441bf34'
branch_labels = None
depends_on = None


def upgrade():
    # Pre-auth rows have no user to attribute them to, and the new columns
    # below are NOT NULL. This app has no real user-generated data yet at
    # this point in its life (take-home project, pre-launch), so clearing
    # them is safe rather than trying to backfill an owner that doesn't
    # exist. Do NOT reuse this pattern once there's real user data.
    op.execute("DELETE FROM files")
    op.execute("DELETE FROM google_oauth_tokens")

    # pg_trgm backs a GIN index that makes ILIKE '%term%' substring search
    # (filename + extracted content) fast at scale, instead of a sequential
    # scan over every row on every keystroke.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('content_text', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['uploaded_by_id'], ['id'])

    with op.batch_alter_table('google_oauth_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###

    op.execute(
        "CREATE INDEX ix_files_name_trgm ON files USING gin (name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_files_content_text_trgm ON files USING gin (content_text gin_trgm_ops)"
    )


def downgrade():
    op.execute("DROP INDEX IF EXISTS ix_files_content_text_trgm")
    op.execute("DROP INDEX IF EXISTS ix_files_name_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_oauth_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('content_text')
        batch_op.drop_column('uploaded_by_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
